### ISSUE TITLE
(eos) Misleading informations

### ISSUE THREAD

**Issue by burningtree** [opencrypto-io/data#16]
https://github.com/opencrypto-io/data/blob/master/db/projects/eos/project.yaml

1) EOS is no longer a ETH token
```
    type: token
    token_properties:
      platform: ethereum
      contract_address: '0x86fa049857e0209aa7d9e616f7eb3b3b78ecfdb0'
      decimals: 18
```
2) EOS mainnet have block_time 0.5s (=500 ms), not 120s (`target_block_time`)
3) The name of the project should be "EOS.IO" instead of "EOS" - depending on how it is referenced on Wikipedia and other sources
4) Mess in images - logo_full should be logo_square, and current logo_square is some outdated logo probably?
